### ISSUE TITLE
Where is the code for abstractive answer?

### ISSUE THREAD

**Issue by guotong1988** [momohuang/FlowQA#10]
![image](https://user-images.githubusercontent.com/4702353/51018531-e90fce80-15b2-11e9-83e9-d8eccf3d5210.png)

@momohuang Thank you!!

**Comment by hsinyuan-huang** [comment]
Hi,

We actually did not perform abstractive answer in FlowQA.
You should give it a try, it may give you some improvements.

**Comment by guotong1988** [comment]
Thank you very much!
