### ISSUE TITLE
Slump in F1 accuracy during prediction

### ISSUE THREAD

**Issue by vnadhan** [momohuang/FlowQA#22]
Hi,

During training, validation is performed (on the dev dataset) per epoch and corresponding F1 is calculated. The best F1 of 64% was found during the 15th epoch(total 30 epochs) and I saved the model at the 15th epoch. Thereafter, I used this model in predict_QuAC to predict on dev dataset. The F1 score after prediction is down to 61%. I am clueless as to why there is a huge reduction in the accuracy, even though the dev dataset is used for both validation and prediction.

Please let me know why there is this slump in accuracy.

Thanks

**Comment by Theerit** [comment]
Hi,
I am not the author of this repo, but I also observe something similar to your case. In my case, I observed that the batch size used during prediction time my have some effect on the performance. The batch size during training time and testing time may need to be the same. Hope this helps.

**Comment by vnadhan** [comment]
Hi Theerit,
The batch size used here has always been 2 for both training and testing. I noticed one difference: in predict_QuA, model.predict uses a No_Ans_Threshold as an argument, however the model.predict in validation does not use this argument. I am researching on why this argument is not used.

**Comment by Theerit** [comment]
If I understand correctly, the prediction in train_QuAC as you mentioned do not use the "no_ans_threshold" argument but rather find the "no_ans_scores" for all questions (in line 220 of train_QuAC). Then these scores are used to find the appropriate threshold that will result in best F1 score (in line 223 of train_QuAC).  To fully reproduce the result shown during the training phase (in your case, 64%), you may need to provide the best threshold as an argument when calling predict_QuAC script as well.

**Comment by vnadhan** [comment]
Thanks a lot, Theerit. Let me try it out.

**Comment by vnadhan** [comment]
Thanks a ton @Theerit! It worked now.
