### ISSUE TITLE
default batchsize is 1？

### ISSUE THREAD

**Issue by guotong1988** [momohuang/FlowQA#9]
![image](https://user-images.githubusercontent.com/4702353/50816806-aa80d680-135c-11e9-9c5b-af6b57d67f22.png)

Thank you very much！
@momohuang

**Comment by hsinyuan-huang** [comment]
This is because each batch is a full dialog and consists of many QA pairs (sometimes about 15+).

**Comment by guotong1988** [comment]
Thank you!
